# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_bearings_rcpp <- function(A, Z) {
    .Call('_gibbonsecr_calc_bearings_rcpp', PACKAGE = 'gibbonsecr', A, Z)
}

calc_distances_rcpp <- function(A, Z) {
    .Call('_gibbonsecr_calc_distances_rcpp', PACKAGE = 'gibbonsecr', A, Z)
}

nearest_rcpp <- function(A, B) {
    .Call('_gibbonsecr_nearest_rcpp', PACKAGE = 'gibbonsecr', A, B)
}

negloglik_rcpp <- function(data, mask, pars, detected, usage, n, S, K, M, a, detfunc_code, bearings_pdf_code, distances_pdf_code) {
    .Call('_gibbonsecr_negloglik_rcpp', PACKAGE = 'gibbonsecr', data, mask, pars, detected, usage, n, S, K, M, a, detfunc_code, bearings_pdf_code, distances_pdf_code)
}

