# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_bearings_rcpp <- function(A, Z) {
    .Call('gibbonsecr_calc_bearings_rcpp', PACKAGE = 'gibbonsecr', A, Z)
}

calc_distances_rcpp <- function(A, Z) {
    .Call('gibbonsecr_calc_distances_rcpp', PACKAGE = 'gibbonsecr', A, Z)
}

negloglik_rcpp <- function(data, mask, pars, detected, usage, n, S, K, M, a, detectfn_code, bearings_pdf_code, distances_pdf_code) {
    .Call('gibbonsecr_negloglik_rcpp', PACKAGE = 'gibbonsecr', data, mask, pars, detected, usage, n, S, K, M, a, detectfn_code, bearings_pdf_code, distances_pdf_code)
}

